### PR TITLE
Fix failure on JSON field

### PR DESCRIPTION
**Pull request by panzacoder**
If a Contentful JSON field exists, when mapping we see that it is of type `object` and assume that it will have field `arrayNode.sys.type`, but this may not exist with custom user-created JSON.

This proposed solution is just to simply check if that field exists before entering the switch on `arrayNode.sys.type` and add the arrayNode directly if it does not exist.

### CODE REVIEW

**Review by joshmossas — CHANGES_REQUESTED** [review]
Hey @panzacoder this looks great. I really appreciate you taking the time to do this.

I just have a couple small changes to request and then I'll get it merged right away.  See my suggestions above.

Also please add a test for this use case to the `./src/main/processEntry/mapper/index.test.ts` file. There's a section for the array fields so you can add it there.

Something like this would prolly be fine:
```ts
    test('Array of Custom Objects', () => {
        const json = [
            {
                firstName: 'Jim',
                lastName: 'Johnson',
            },
            {
                firstName: 'Rebecca',
                lastName: 'Johnson',
            },
        ];
        const fieldValue = mapArrayField(json);
        expect(fieldValue[0].firstName).toBe('Jim');
        expect(fieldValue[1].firstName).toBe('Rebecca');
    });
```

**Comment by joshmossas** [comment]
Hey @panzacoder it looks good it's just missing a test in `./src/main/processEntry/mapper/index.test.ts`. The example I provided in my first comment should suffice

**Review by joshmossas — APPROVED** [review]

**Comment by joshmossas** [comment]
I ended up merging it and adding a test. Thanks for contributing. I appreciate it. 😄

**Comment by panzacoder** [comment]
@joshmossas Sorry for the delay! I had a WIP for the test here locally but didn't see any additional tests run when I did `npm test` so I was going to revisit today.

Thank you for merging in and adding the test! I really appreciate this library. It's a lifesaver.

**Comment by joshmossas** [comment]
Cool I'm glad you find it useful! 😄

**Pull request merged**
